name: Verify

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        java-version: ['8', '11', '17']
    name: Verify
    uses: takari/takari-gh-actions/.github/workflows/ci.yml@v1
    with:
      java-version: ${{ matrix.java-version }}
