name: Verify

on:
  push:
    branches:
      - master
  pull_request:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        java: [ 8, 11, 17, 21 ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Set up JDK ${{ matrix.java }}"
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Build & Test
        run: ./mvnw -B verify
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: polyglot-ruby-it-use_jruby_installation-build.log
          path: polyglot-ruby/target/it/use_jruby_installation/build.log
          retention-days: 1
